refactor: merge ecosystem and xwayland into misc.lua

diff --git a/home/dot_zshenv b/home/dot_zshenv
--- a/home/dot_zshenv
+++ b/home/dot_zshenv
@@ -3,4 +3,7 @@
 XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
 export ZDOTDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}"
 
-[[ -r "$ZDOTDIR/.zshenv" ]] && source "$ZDOTDIR/.zshenv"
+if ! source $ZDOTDIR/.zshenv; then
+    echo "FATAL Error: Could not source $ZDOTDIR/.zshenv"
+    return 1
+fi
